export const WATERFALL_MIN_TILE_WIDTH = 208;
export const WATERFALL_GAP = 10;
export const FILMSTRIP_THUMB_HEIGHT = 92;
export const CHROME_ANIMATION_DURATION_MS = 320;
export const CONTEXT_MENU_WIDTH = 248;
export const CONTEXT_MENU_HEIGHT = 168;
export const CONTEXT_MENU_VIEWPORT_PADDING = 12;

export const DEFAULT_SIDEBAR_WIDTH = 252;
export const DEFAULT_DETAIL_PANEL_WIDTH = 292;
export const DEFAULT_FILMSTRIP_HEIGHT = 136;

export const SIDEBAR_MIN_WIDTH = 220;
export const SIDEBAR_MAX_WIDTH = 420;
export const DETAIL_PANEL_MIN_WIDTH = 252;
export const DETAIL_PANEL_MAX_WIDTH = 480;
export const FILMSTRIP_MIN_HEIGHT = 112;
export const FILMSTRIP_MAX_HEIGHT = 260;